// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/jballerina.java;
import ballerina/time;

const DEFAULT_DEEPSEEK_SERVICE_URL = "https://api.deepseek.com";
const DEFAULT_MAX_TOKEN_COUNT = 512;
const DEFAULT_TEMPERATURE = 0.7d;

# Deepseek is a client class that provides an interface for interacting with Deepseek Large Language Models.
public isolated client class ModelProvider {
    *ai:ModelProvider;
    private final http:Client llmClient;
    private final int maxTokens;
    private final DEEPSEEK_MODEL_NAMES modelType;
    private final decimal temperature;

    # Initializes the Deepseek model client with the provided configurations.
    #
    # + apiKey - The Deepseek API Key
    # + model - The Deepseek model name
    # + serviceUrl - The base URL of Deepseek API endpoint
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperateure - The temperature for controlling randomness in the model's output
    # + connectionConfig - Additional HTTP client configurations
    # + return - `nil` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "API Key"} string apiKey,
            @display {label: "Model Type"} DEEPSEEK_MODEL_NAMES modelType = DEEPSEEK_CHAT,
            @display {label: "Service URL"} string serviceUrl = DEFAULT_DEEPSEEK_SERVICE_URL,
            @display {label: "Maximum Token"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal temperature = DEFAULT_TEMPERATURE,
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig
    ) returns ai:Error? {

        http:ClientConfiguration deepseekConfig = {
            auth: {token: apiKey},
            httpVersion: connectionConfig.httpVersion,
            http1Settings: connectionConfig.http1Settings ?: {},
            http2Settings: connectionConfig?.http2Settings ?: {},
            timeout: connectionConfig.timeout,
            forwarded: connectionConfig.forwarded,
            poolConfig: connectionConfig?.poolConfig,
            cache: connectionConfig?.cache ?: {},
            compression: connectionConfig.compression,
            circuitBreaker: connectionConfig?.circuitBreaker,
            retryConfig: connectionConfig?.retryConfig,
            responseLimits: connectionConfig?.responseLimits ?: {},
            secureSocket: connectionConfig?.secureSocket,
            proxy: connectionConfig?.proxy,
            validation: connectionConfig.validation
        };

        http:Client|error httpClient = new http:Client(serviceUrl, deepseekConfig);

        if httpClient is error {
            return error ai:Error("Failed to initialize Deepseek client", httpClient);
        }

        self.maxTokens = maxTokens;
        self.modelType = modelType;
        self.llmClient = httpClient;
        self.temperature = temperature;
    }

    # Generates a chat completion message from a Deepseek model
    #
    # + messages - List of chat messages or a user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages, ai:ChatCompletionFunctions[] tools, string? stop = ())
    returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("deepseek");
        if stop is string {
            span.addStopSequence(stop);
        }
        span.addTemperature(self.temperature);
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }
        DeepSeekChatRequestMessages[]|ai:Error deepseekPayloadMessages = self.prepareDeepseekRequestMessages(messages);
        if deepseekPayloadMessages is ai:Error {
            span.close(deepseekPayloadMessages);
            return deepseekPayloadMessages;
        }

        DeepSeekChatCompletionRequest request = {
            temperature: self.temperature,
            messages: deepseekPayloadMessages,
            model: self.modelType,
            max_tokens: self.maxTokens,
            stop: stop
        };

        if tools.length() > 0 {
            span.addTools(tools);
            request.tools = self.buildDeepseekTools(tools);
        }

        DeepSeekChatCompletionResponse|error response = self.llmClient->/chat/completions.post(request);
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            span.close(err);
            return err;
        }
        
        span.addResponseId(response.id);
        int? inputTokens = response.usage?.prompt_tokens;
        if inputTokens is int {
            span.addInputTokenCount(inputTokens);
        }
        int? outputTokens = response.usage?.completion_tokens;
        if outputTokens is int {
            span.addOutputTokenCount(outputTokens);
        }

        DeepseekChatResponseChoice[]? choices = response.choices;
        string? finishReason = choices !is () && choices.length() > 0 ? choices[0].finish_reason : ();
        if finishReason is string {
            span.addFinishReason(finishReason);
        }
        ai:ChatAssistantMessage|ai:Error result = self.getAssistantMessages(response);
        if result is ai:Error {
            span.close(result);
            return result;
        }

        span.addOutputMessages(result);
        span.addOutputType(observe:TEXT);
        span.close();
        return result;
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>)
                returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.deepseek.Generator"
    } external;

    # Sends a streaming chat request to the Deepseek model with the given messages and tools.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - A stream of chat completion chunks, or an error in case of failures
    isolated remote function chatStream(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools = [], string? stop = ())
            returns stream<ai:ChatCompletionChunk, ai:Error?>|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("deepseek");
        if stop is string {
            span.addStopSequence(stop);
        }
        span.addTemperature(self.temperature);
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        DeepSeekChatRequestMessages[]|ai:Error deepseekPayloadMessages = self.prepareDeepseekRequestMessages(messages);
        if deepseekPayloadMessages is ai:Error {
            span.close(deepseekPayloadMessages);
            return deepseekPayloadMessages;
        }
        DeepSeekChatCompletionRequest request = {
            temperature: self.temperature,
            messages: deepseekPayloadMessages,
            model: self.modelType,
            max_tokens: self.maxTokens,
            stop,
            'stream: true,
            stream_options: {include_usage: true}
        };

        if tools.length() > 0 {
            span.addTools(tools);
            request.tools = self.buildDeepseekTools(tools);
        }

        stream<http:SseEvent, error?>|ai:Error sseStream = openSseStream(self.llmClient, "/chat/completions", request);
        if sseStream is ai:Error {
            span.close(sseStream);
            return sseStream;
        }
        stream<ai:ChatCompletionChunk, ai:Error?> chunkStream = new (new DeepSeekChunkIterator(sseStream, span));
        return chunkStream;
    }

    # Sends a streaming chat request to the model using the given prompt and streams
    # back the generated answer. Only `string` is supported as the expected type.
    #
    # Only the answer text is streamed. On `deepseek-reasoner` the chain-of-thought that
    # precedes the answer is dropped; use `chatStream` and read `delta.reasoning` to
    # observe it.
    #
    # + prompt - The prompt to use in the chat request
    # + td - The expected type of the streamed value; must be `string`
    # + return - A stream of the generated value, or an error if the type is unsupported
    remote function generateStream(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>)
            returns stream<td, ai:Error?>|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.deepseek.StreamGenerator"
    } external;

    private isolated function transFormFuncToTool(DeepseekFunction deepseekFunction) returns DeepseekTool
        => {'function: deepseekFunction};

    # Converts the `ai` tool definitions into the Deepseek tool payload. Shared by `chat`
    # and `chatStream` so both paths declare tools to the model in exactly the same way.
    #
    # + tools - The tool definitions to convert
    # + return - The tools in the Deepseek request shape
    private isolated function buildDeepseekTools(ai:ChatCompletionFunctions[] tools) returns DeepseekTool[] {
        DeepseekFunction[] deepseekFunctions = [];
        foreach ai:ChatCompletionFunctions toolFunction in tools {
            map<json>? parameters = toolFunction.parameters;
            // Deepseek does not allow the NULL type when a function has no parameters,
            // so avoid sending the schema in such cases.
            if parameters is map<json> && parameters.'type == ai:NULL {
                parameters = ();
            }
            deepseekFunctions.push({
                name: toolFunction.name,
                description: toolFunction.description,
                parameters
            });
        }
        return deepseekFunctions.'map(self.transFormFuncToTool);
    }

    # Generates a random tool ID.
    #
    # + return - A random tool ID string
    private isolated function generateNewToolId() returns string {
        decimal timestampForToolCallId = time:monotonicNow();
        string strTimestamp = timestampForToolCallId.toString();
        string toolCallId = re `\.`.replace(strTimestamp, "");
        string newToolCallId = toolCallId.substring(toolCallId.length() - 9);
        return newToolCallId;
    }

    # Retrieves the ID of the last tool call from a deepseek chat assistant message.
    #
    # + deepseekPayloadMessages - Array of DeepSeek chat messages
    # + return - ID of the first tool call from the most recent assistant message, or empty `ai:Error`
    private isolated function getAssistantToolCallId(DeepSeekChatRequestMessages[] deepseekPayloadMessages)
    returns string|ai:LlmError {
        // Iterate from the end of the array to find the last assistant message
        int index = deepseekPayloadMessages.length() - 1;
        while (index >= 0) {
            DeepSeekChatRequestMessages message = deepseekPayloadMessages[index];
            if message is DeepseekChatAssistantMessage && message.tool_calls is DeepseekChatResponseToolCall[] {
                DeepseekChatResponseToolCall[]? tools = message.tool_calls;
                if tools is () {
                    return error("No tool calls found in the assistant message");
                }
                if tools.length() > 0 {
                    return tools[0].id;
                }
            }
            index = index - 1;
        }
        return "";
    }

    private isolated function prepareDeepseekRequestMessages(ai:ChatMessage[]|ai:ChatUserMessage messages)
        returns DeepSeekChatRequestMessages[]|ai:Error {
        DeepSeekChatRequestMessages[] deepseekMessages = [];
        if messages is ai:ChatUserMessage {
            deepseekMessages.push(check self.mapToDeepseekMessage(messages));
            return deepseekMessages;
        }
        foreach ai:ChatMessage message in messages {
            if message is ai:ChatUserMessage|ai:ChatSystemMessage {
                deepseekMessages.push(check self.mapToDeepseekMessage(message));
            } else if message is ai:ChatAssistantMessage {
                ai:FunctionCall[]? toolCalls = message.toolCalls;
                DeepseekChatAssistantMessage deepseekAssistantMessage = {role: ai:ASSISTANT, content: message.content};
                if toolCalls is ai:FunctionCall[] {
                    DeepseekChatResponseToolCall[] toolCall = [];
                    foreach ai:FunctionCall 'function in toolCalls {
                        DeepseekChatResponseFunction functionCall = {
                            name: 'function.name,
                            arguments: 'function.arguments.toJsonString()
                        };
                        DeepseekChatResponseToolCall tool = {
                            'function: functionCall,
                            id: 'function.id ?: self.generateNewToolId(),
                            'type: FUNCTION
                        };
                        toolCall.push(tool);
                    }
                    deepseekAssistantMessage.tool_calls = toolCall;
                }
                deepseekMessages.push(deepseekAssistantMessage);
            } else {
                DeepseekChatToolMessage deepseekToolMessage = {
                    role: TOOL_ROLE,
                    content: message?.content is string ? {result: message.content}.toJsonString() : "",
                    tool_call_id: message.id ?: check self.getAssistantToolCallId(deepseekMessages)
                };
                deepseekMessages.push(deepseekToolMessage);
            }
        }
        return deepseekMessages;
    }

    # Extracts assistant messages from a Deepseek chat completion response.
    #
    # + response - The response from LLM
    # + return - Chat response or an error in-case of failures
    private isolated function getAssistantMessages(DeepSeekChatCompletionResponse response)
    returns ai:ChatAssistantMessage|ai:LlmError {
        DeepseekChatResponseChoice[]? choices = response.choices;
        if choices is () || choices.length() == 0 {
            return error ai:LlmInvalidResponseError("Empty response from the model when using function call API");
        }
        DeepseekChatResponseMessage message = choices[0].message;
        string? content = message?.content;
        DeepseekChatResponseToolCall[]? toolCalls = message?.tool_calls;
        if toolCalls is () {
            return {role: ai:ASSISTANT, content: content};
        }

        ai:FunctionCall[] functionCalls = [];
        foreach DeepseekChatResponseToolCall toolCall in toolCalls {
            functionCalls.push(check self.mapToFunctionCall(toolCall));
        }
        return {role: ai:ASSISTANT, toolCalls: functionCalls, content: content};
    }

    private isolated function mapToFunctionCall(DeepseekChatResponseToolCall toolCall)
    returns ai:FunctionCall|ai:LlmError {
        do {
            json jsonArgs = check toolCall.'function.arguments.fromJsonString();
            map<json>? arguments = check jsonArgs.cloneWithType();
            return {name: toolCall.'function.name, arguments, id: toolCall.id};
        } on fail error e {
            return error("Invalid or malformed arguments received in function call response.", e);
        }
    }

    private isolated function mapToDeepseekMessage(ai:ChatUserMessage|ai:ChatSystemMessage message)
    returns DeepseekChatUserMessage|DeepseekChatSystemMessage|ai:Error {
        if message is ai:ChatUserMessage {
            DeepseekChatUserMessage userMessage = {
                role: ai:USER,
                content: check getChatMessageStringContent(message.content)
            };
            return userMessage;
        }

        DeepseekChatSystemMessage systemMessage = {
            role: ai:SYSTEM,
            content: check getChatMessageStringContent(message.content)
        };
        return systemMessage;
    }
}

isolated function getChatMessageStringContent(ai:Prompt|string prompt) returns string|ai:Error {
    if prompt is string {
        return prompt;
    }
    string[] & readonly strings = prompt.strings;
    anydata[] insertions = prompt.insertions;
    string promptStr = strings[0];
    foreach int i in 0 ..< insertions.length() {
        string str = strings[i + 1];
        anydata insertion = insertions[i];

        if insertion is ai:TextDocument|ai:TextChunk {
            promptStr += insertion.content + " " + str;
            continue;
        }

        if insertion is ai:TextDocument[] {
            foreach ai:TextDocument doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:TextChunk[] {
            foreach ai:TextChunk doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:Document {
            return error ai:Error("Only Text Documents are currently supported.");
        }

        promptStr += insertion.toString() + str;
    }
    return promptStr.trim();
}

isolated function convertMessageToJson(ai:ChatMessage[]|ai:ChatMessage messages) returns json|ai:Error {
    if messages is ai:ChatMessage[] {
        return messages.'map(msg => msg is ai:ChatUserMessage|ai:ChatSystemMessage ? check convertMessageToJson(msg) : msg);
    }
    if messages is ai:ChatUserMessage|ai:ChatSystemMessage {

    }
    return messages !is ai:ChatUserMessage|ai:ChatSystemMessage ? messages :
        {role: messages.role, content: check getChatMessageStringContent(messages.content), name: messages.name};
}

# Sends a streaming request and opens the Server-Sent Events stream it answers with.
#
# The POST binds to `http:Response` because the payload has to be read as an event stream
# rather than data-bound, and that also switches off the client's status-code error
# mapping - so the status is checked here. Without it DeepSeek's own message for an expired
# key, an insufficient balance, or a rate limit is discarded, and `getSseEventStream` fails
# the content-type check instead, telling the caller only that the stream could not be
# opened.
#
# + llmClient - The HTTP client for the DeepSeek API
# + path - The endpoint path to post to
# + request - The request payload
# + return - The SSE event stream, or an `ai:Error` describing the failure
isolated function openSseStream(http:Client llmClient, string path, anydata request)
        returns stream<http:SseEvent, error?>|ai:Error {
    http:Response|error response = llmClient->post(path, request);
    if response is error {
        return error ai:LlmConnectionError("Error while connecting to the model for streaming", response);
    }
    int statusCode = response.statusCode;
    if statusCode < 200 || statusCode >= 300 {
        string? detail = extractHttpErrorDetail(response);
        string message = detail is string
            ? string `The model rejected the streaming request with status ${statusCode}: ${detail}`
            : string `The model rejected the streaming request with status ${statusCode}`;
        return error ai:LlmConnectionError(message);
    }
    stream<http:SseEvent, error?>|error sseStream = response.getSseEventStream();
    if sseStream is error {
        return error ai:LlmConnectionError("Failed to open the SSE stream from the model", sseStream);
    }
    return sseStream;
}

# Pulls the human-readable detail out of a non-2xx streaming response, which carries the
# usual DeepSeek `{"error": {"message": ...}}` body rather than an event stream. Reading it
# also drains the payload, so the connection is released back to the pool.
#
# + response - The non-2xx response
# + return - The failure detail, or `()` when the body carries none
isolated function extractHttpErrorDetail(http:Response response) returns string? {
    json|error payload = response.getJsonPayload();
    if payload is error {
        string|error text = response.getTextPayload();
        if text is string && text.trim() != "" {
            return text.trim();
        }
        return ();
    }
    string? detail = extractStreamErrorFrame(payload);
    if detail is string {
        return detail;
    }
    return payload.toJsonString();
}

# Iterator that converts DeepSeek's Server-Sent Event stream into a stream of
# normalized `ai:ChatCompletionChunk` values. Each `data:` line is parsed into the
# DeepSeek wire chunk and mapped via `toAiChunk`; the terminating `[DONE]` sentinel ends
# the stream, and blank lines are skipped. The chat span is closed once the stream is
# done, whether it ended cleanly, failed, or was closed by the caller.
#
# A frame that cannot be parsed is reported as an error rather than skipped: DeepSeek
# emits `{"error": {...}}` mid-stream when a generation is cut short, and skipping it
# would end the stream silently, handing the caller a truncated answer that looks
# complete - or, if every frame is unparseable, an empty answer that looks successful.
class DeepSeekChunkIterator {
    private stream<http:SseEvent, error?> sseStream;
    private observe:ChatSpan span;
    private boolean done = false;

    isolated function init(stream<http:SseEvent, error?> sseStream, observe:ChatSpan span) {
        self.sseStream = sseStream;
        self.span = span;
    }

    public isolated function next() returns record {|ai:ChatCompletionChunk value;|}|ai:Error? {
        if self.isDone() {
            return ();
        }
        while true {
            record {|http:SseEvent value;|}|error? event = self.sseStream.next();
            if event is () {
                return self.finish();
            }
            if event is error {
                return self.failStream(error ai:LlmConnectionError("Error while reading the model stream", event));
            }
            string? data = event.value.data;
            if data is () {
                continue;
            }
            string trimmedData = data.trim();
            if trimmedData == "" {
                continue;
            }
            if trimmedData == "[DONE]" {
                return self.finish();
            }
            json|error payload = trimmedData.fromJsonString();
            if payload is error {
                return self.failStream(error ai:LlmInvalidResponseError(
                        "Invalid or malformed chunk received from the model", payload));
            }
            string? errorMessage = extractStreamErrorFrame(payload);
            if errorMessage is string {
                return self.failStream(error ai:LlmError(
                        string `Error received mid-stream from the model: ${errorMessage}`));
            }
            DeepSeekChatCompletionChunk|error wireChunk = payload.cloneWithType();
            if wireChunk is error {
                return self.failStream(error ai:LlmInvalidResponseError(
                        "Unexpected chunk shape received from the model", wireChunk));
            }
            ai:ChatCompletionChunk chunk = toAiChunk(wireChunk);
            self.recordChunk(chunk);
            return {value: chunk};
        }
    }

    public isolated function close() returns ai:Error? {
        if !self.markDone() {
            self.span.close();
        }
        error? result = self.sseStream.close();
        if result is error {
            return error ai:LlmConnectionError("Error while closing the model stream", result);
        }
        return ();
    }

    // Records the finish reason and usage the span reports for the completed generation.
    // Usage arrives on the final chunk, which `stream_options.include_usage` asks for.
    private isolated function recordChunk(ai:ChatCompletionChunk chunk) {
        ai:ChatCompletionChunkChoice[] choices = chunk.choices;
        if choices.length() > 0 {
            ai:FinishReason? finishReason = choices[0].finishReason;
            if finishReason is ai:FinishReason {
                self.span.addFinishReason(finishReason);
                self.span.addOutputType(observe:TEXT);
            }
        }
        ai:CompletionTokenUsage? usage = chunk?.usage;
        if usage is ai:CompletionTokenUsage {
            int? promptTokens = usage?.promptTokens;
            if promptTokens is int {
                self.span.addInputTokenCount(promptTokens);
            }
            int? completionTokens = usage?.completionTokens;
            if completionTokens is int {
                self.span.addOutputTokenCount(completionTokens);
            }
        }
    }

    // Ends the stream cleanly, closing the span exactly once.
    private isolated function finish() returns () {
        if !self.markDone() {
            self.span.close();
        }
        return ();
    }

    // Ends the stream with an error, closing the span exactly once.
    private isolated function failStream(ai:Error err) returns ai:Error {
        if !self.markDone() {
            self.span.close(err);
        }
        return err;
    }

    private isolated function isDone() returns boolean {
        lock {
            return self.done;
        }
    }

    // Marks the stream as done, returning whether it was already marked before this call.
    private isolated function markDone() returns boolean {
        lock {
            boolean wasDone = self.done;
            self.done = true;
            return wasDone;
        }
    }
}

# Builds the string stream behind the dependently-typed `generateStream`. The
# native `StreamGenerator` shim trampolines here so the type gating stays in
# Ballerina. Only `string` is supported; other types yield an error because a
# partial generation is a valid value only for `string`. When valid, the
# underlying `chatStream` chunks are projected onto their text fragments.
#
# + llmModel - The model provider whose `chatStream` supplies the chunks
# + prompt - The prompt to send to the model
# + td - The caller's expected type; must be `string`
# + return - A stream of text fragments, or an error if the type is unsupported
function generateLlmResponseStream(ModelProvider llmModel, ai:Prompt prompt, typedesc<anydata> td)
        returns stream<string, ai:Error?>|ai:Error {
    if td !is typedesc<string> {
        return error ai:Error("This data type is not supported for streaming. " +
            "'generateStream' supports only 'string'; use 'generate' for structured types.");
    }
    stream<ai:ChatCompletionChunk, ai:Error?> chunks = check llmModel->chatStream({role: ai:USER, content: prompt});
    stream<string, ai:Error?> textStream = new (new ChunkTextIterator(chunks));
    return textStream;
}

# Projects a normalized `ai:ChatCompletionChunk` stream onto its text content,
# yielding each non-empty `delta.content` fragment and skipping tool-call and
# usage-only chunks. Backs `generateLlmResponseStream`.
class ChunkTextIterator {
    private stream<ai:ChatCompletionChunk, ai:Error?> chunks;

    isolated function init(stream<ai:ChatCompletionChunk, ai:Error?> chunks) {
        self.chunks = chunks;
    }

    public isolated function next() returns record {|string value;|}|ai:Error? {
        while true {
            record {|ai:ChatCompletionChunk value;|}|ai:Error? next = self.chunks.next();
            if next is () {
                return ();
            }
            if next is ai:Error {
                return next;
            }
            ai:ChatCompletionChunkChoice[] choices = next.value.choices;
            if choices.length() == 0 {
                continue;
            }
            string? content = choices[0].delta.content;
            if content is string && content.length() > 0 {
                return {value: content};
            }
        }
    }

    public isolated function close() returns ai:Error? {
        return self.chunks.close();
    }
}
