// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/http;

public enum DEEPSEEK_MODEL_NAMES {
    DEEPSEEK_CHAT = "deepseek-chat",
    DEEPSEEK_REASONER = "deepseek-reasoner"
}

# Configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Configuration"}
public type ConnectionConfig record {|

    # The HTTP version understood by the client
    @display {label: "HTTP Version"}
    http:HttpVersion httpVersion = http:HTTP_2_0;

    # Configurations related to HTTP/1.x protocol
    @display {label: "HTTP1 Settings"}
    http:ClientHttp1Settings http1Settings?;

    # Configurations related to HTTP/2 protocol
    @display {label: "HTTP2 Settings"}
    http:ClientHttp2Settings http2Settings?;

    # The maximum time to wait (in seconds) for a response before closing the connection
    @display {label: "Timeout"}
    decimal timeout = 60;

    # The choice of setting `forwarded`/`x-forwarded` header
    @display {label: "Forwarded"}
    string forwarded = "disable";

    # Configurations associated with request pooling
    @display {label: "Pool Configuration"}
    http:PoolConfiguration poolConfig?;

    # HTTP caching related configurations
    @display {label: "Cache Configuration"}
    http:CacheConfig cache?;

    # Specifies the way of handling compression (`accept-encoding`) header
    @display {label: "Compression"}
    http:Compression compression = http:COMPRESSION_AUTO;

    # Configurations associated with the behaviour of the Circuit Breaker
    @display {label: "Circuit Breaker Configuration"}
    http:CircuitBreakerConfig circuitBreaker?;

    # Configurations associated with retrying
    @display {label: "Retry Configuration"}
    http:RetryConfig retryConfig?;

    # Configurations associated with inbound response size limits
    @display {label: "Response Limit Configuration"}
    http:ResponseLimitConfigs responseLimits?;

    # SSL/TLS-related options
    @display {label: "Secure Socket Configuration"}
    http:ClientSecureSocket secureSocket?;

    # Proxy server related options
    @display {label: "Proxy Configuration"}
    http:ProxyConfig proxy?;

    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    @display {label: "Payload Validation"}
    boolean validation = true;
|};

public type DeepseekChatResponseFunction record {
    string name;
    string arguments;
};

type DeepseekChatResponseToolCall record {
    string id;
    string 'type;
    DeepseekChatResponseFunction 'function;
};

type DeepseekChatResponseMessage record {
    string role;
    string? content = ();
    # Chain-of-thought reasoning produced by the deepseek-reasoner model, if any
    string? reasoning_content = ();
    DeepseekChatResponseToolCall[]? tool_calls = ();
};

type DeepseekChatResponseChoice record {
    DeepseekChatResponseMessage message;
    string finish_reason?;
};

// https://api-docs.deepseek.com/api/create-chat-completion#responses
type DeepSeekChatCompletionResponse record {
    string id;
    DeepseekChatResponseChoice[] choices;
    DeepSeekUsage usage?;
};

type DeepSeekUsage record {
    int prompt_tokens;
    int completion_tokens;
    # Total number of tokens used (prompt + completion)
    int total_tokens?;
    # Number of prompt tokens served from cache (DeepSeek context caching)
    int prompt_cache_hit_tokens?;
    # Number of prompt tokens not found in cache (DeepSeek context caching)
    int prompt_cache_miss_tokens?;
    # Breakdown of the tokens used in the completion
    DeepSeekCompletionTokensDetails completion_tokens_details?;
};

# Breakdown of tokens used in a completion
type DeepSeekCompletionTokensDetails record {
    # Tokens generated by the model for reasoning (deepseek-reasoner only)
    int reasoning_tokens?;
};

// ── Streaming types (Chat Completions `chat.completion.chunk`) ───────────────
// DeepSeek streams the Chat Completions API as SSE, one `chat.completion.chunk`
// per event. OpenAI-compatible, plus DeepSeek's `reasoning_content` delta field
// emitted by the `deepseek-reasoner` model (chain-of-thought before the answer).

# A streamed chunk of a chat completion response (object: "chat.completion.chunk")
type DeepSeekChatCompletionChunk record {
    # Unique identifier for the completion, shared across all chunks
    string id;
    # Object type, always "chat.completion.chunk"
    string 'object;
    # Unix timestamp (seconds) when the completion was created
    int created;
    # The model used (e.g., "deepseek-chat", "deepseek-reasoner")
    string model;
    # Fingerprint of the backend configuration the model runs with
    string system_fingerprint;
    # Choices in this chunk; empty in the final usage-only chunk
    DeepSeekChatChunkChoice[] choices;
    # Token usage, present only in the final chunk when stream_options.include_usage is set
    DeepSeekUsage usage?;
};

# A single choice within a streamed chunk
type DeepSeekChatChunkChoice record {
    # Index of the choice in the list of choices
    int index;
    # The incremental content for this choice
    DeepSeekChatChunkDelta delta;
    # Reason the model stopped, null until the final chunk for this choice
    # (e.g., "stop", "length", "content_filter", "tool_calls", "insufficient_system_resource")
    string? finish_reason = ();
    # Log probability information for the choice, null when not requested
    DeepSeekChatChunkLogprobs? logprobs = ();
};

# Log probability information for a streamed choice
type DeepSeekChatChunkLogprobs record {
    # Log probabilities of the content tokens, null when not requested
    DeepSeekChatTokenLogprob[]? content = ();
    # Log probabilities of the reasoning_content tokens (deepseek-reasoner only)
    DeepSeekChatTokenLogprob[]? reasoning_content = ();
};

# Log probability details for a single token
type DeepSeekChatTokenLogprob record {
    # The token
    string token;
    # The log probability of this token
    decimal logprob;
    # UTF-8 byte representation of the token, null when no byte representation exists
    int[]? bytes = ();
    # The most likely tokens and their log probabilities at this position
    DeepSeekChatTopLogprob[] top_logprobs;
};

# A candidate token and its log probability at a given position
type DeepSeekChatTopLogprob record {
    # The token
    string token;
    # The log probability of this token
    decimal logprob;
    # UTF-8 byte representation of the token, null when no byte representation exists
    int[]? bytes = ();
};

# The incremental delta for a streamed choice
type DeepSeekChatChunkDelta record {
    # Role of the author, sent only on the first delta (typically "assistant")
    string role?;
    # Text content chunk of the final answer
    string? content = ();
    # Chain-of-thought reasoning chunk (deepseek-reasoner only); streamed before `content`
    string? reasoning_content = ();
    # Incremental tool calls being streamed
    DeepSeekChunkToolCall[]? tool_calls = ();
};

# An incremental tool call within a streamed delta
type DeepSeekChunkToolCall record {
    # Index of the tool call, used to accumulate fragments across chunks
    int index;
    # Unique identifier for the tool call, sent on the first fragment
    string id?;
    # Tool type, sent on the first fragment (always "function")
    string 'type?;
    # The function name/arguments fragment
    DeepSeekChunkToolCallFunction 'function?;
};

# Function name/arguments fragment in a streamed tool call
type DeepSeekChunkToolCallFunction record {
    # Name of the function, sent on the first fragment
    string name?;
    # Partial JSON string chunk of the function arguments; accumulate across chunks
    string arguments?;
};

type DeepseekChatSystemMessage record {|
    string content;
    string role = ai:SYSTEM;
|};

type DeepseekChatAssistantMessage record {
    string? content = ();
    string role = "assistant";
    DeepseekChatResponseToolCall[]? tool_calls = ();
};

const TOOL_ROLE = "tool";
const FUNCTION = "function";

type DeepseekChatToolMessage record {|
    string content;
    string role = TOOL_ROLE;
    string tool_call_id;
|};

type DeepseekChatUserMessage record {|
    string content;
    string role = ai:USER;
|};

type DeepSeekChatRequestMessages DeepseekChatSystemMessage|DeepseekChatUserMessage
    |DeepseekChatAssistantMessage|DeepseekChatToolMessage;

type DeepseekFunction record {|
    string name;
    string description;
    map<json> parameters?;
|};

type DeepseekTool record {|
    string 'type = FUNCTION;
    DeepseekFunction 'function;
|};

type DeepSeekToolChoice record {|
    FUNCTION 'type?;
    record {|
        string name;
    |} 'function?;
|};

type DeepSeekChatCompletionRequest record {|
    DeepSeekChatRequestMessages[] messages;
    DEEPSEEK_MODEL_NAMES model;
    int? max_tokens;
    string?|string[]? stop = ();
    decimal? temperature = 1;
    DeepseekTool[]? tools = ();
    DeepSeekToolChoice? toolChoice = ();
    # When set, partial deltas are streamed back as Server-Sent Events
    boolean 'stream?;
    # Options controlling the streamed response; e.g. request the final usage chunk
    DeepSeekStreamOptions stream_options?;
|};

# Options that shape the streamed chat completion response
type DeepSeekStreamOptions record {|
    # When true, an additional final chunk carries the request's token usage
    boolean include_usage;
|};

// ── Wire → normalized mapping ──────────────────────────────────────────────
// Projects a DeepSeek `chat.completion.chunk` (the streaming wire types above)
// onto the normalized `ai:ChatCompletionChunk` that `chatStream` must return.
// Only the subset the `ai` type can hold is mapped; everything else is ignored.

# Maps a DeepSeek wire chunk onto the normalized `ai:ChatCompletionChunk`.
# Forwards tool calls on every chunk (not just the first) so argument fragments
# stream through correctly, and maps `reasoning_content` onto `delta.reasoning`.
#
# + w - The parsed DeepSeek wire chunk
# + return - The normalized chunk consumed by the `ai` module
isolated function toAiChunk(DeepSeekChatCompletionChunk w) returns ai:ChatCompletionChunk {
    ai:ChatCompletionChunkChoice[] choices = [];
    foreach DeepSeekChatChunkChoice c in w.choices {
        ai:ChatCompletionChunkDelta delta = {content: c.delta.content};
        ai:ROLE? role = mapRole(c.delta?.role);
        if role is ai:ROLE {
            delta.role = role;
        }
        string? reasoning = c.delta?.reasoning_content;
        if reasoning is string {
            delta.reasoning = reasoning;
        }
        DeepSeekChunkToolCall[]? wireToolCalls = c.delta?.tool_calls;
        if wireToolCalls is DeepSeekChunkToolCall[] {
            ai:ToolCallChunk[] toolCalls = [];
            foreach DeepSeekChunkToolCall t in wireToolCalls {
                ai:ToolCallChunk toolCall = {index: t.index};
                string? id = t?.id;
                if id is string {
                    toolCall.id = id;
                }
                DeepSeekChunkToolCallFunction? fn = t?.'function;
                if fn is DeepSeekChunkToolCallFunction {
                    ai:FunctionCallChunk functionFragment = {};
                    string? name = fn?.name;
                    if name is string {
                        functionFragment.name = name;
                    }
                    string? arguments = fn?.arguments;
                    if arguments is string {
                        functionFragment.arguments = arguments;
                    }
                    toolCall.'function = functionFragment;
                }
                toolCalls.push(toolCall);
            }
            delta.toolCalls = toolCalls;
        }
        choices.push({index: c.index, delta, finishReason: mapFinishReason(c.finish_reason)});
    }

    ai:ChatCompletionChunk chunk = {id: w.id, model: w.model, choices};
    DeepSeekUsage? usage = w.usage;
    if usage is DeepSeekUsage {
        ai:CompletionTokenUsage tokenUsage = {
            promptTokens: usage.prompt_tokens,
            completionTokens: usage.completion_tokens
        };
        int? totalTokens = usage.total_tokens;
        if totalTokens is int {
            tokenUsage.totalTokens = totalTokens;
        }
        chunk.usage = tokenUsage;
    }
    return chunk;
}

# Safely maps a DeepSeek role string onto the `ai:ROLE` enum; returns `()` for
# absent or unrecognized values rather than panicking on a cast.
#
# + role - The role string from the wire delta
# + return - The mapped `ai:ROLE`, or `()` when absent/unrecognized
isolated function mapRole(string? role) returns ai:ROLE? {
    // Streamed response deltas only carry the "assistant" role; "system"/"user"
    // are handled for completeness. ("function" is request-only and the `ai`
    // enum member is not accessible here, so it is intentionally omitted.)
    match role {
        "system" => {
            return ai:SYSTEM;
        }
        "user" => {
            return ai:USER;
        }
        "assistant" => {
            return ai:ASSISTANT;
        }
    }
    return ();
}

# Safely maps a DeepSeek finish reason onto the `ai:FinishReason` enum. Returns
# `()` for absent or unrecognized values (e.g. DeepSeek's
# `insufficient_system_resource`) rather than panicking on a cast.
#
# + finishReason - The finish reason from the wire chunk
# + return - The mapped `ai:FinishReason`, or `()` when absent/unrecognized
isolated function mapFinishReason(string? finishReason) returns ai:FinishReason? {
    match finishReason {
        "stop" => {
            return ai:STOP;
        }
        "length" => {
            return ai:LENGTH;
        }
        "tool_calls"|"function_call" => {
            return ai:TOOL_CALLS;
        }
        "content_filter" => {
            return ai:CONTENT_FILTER;
        }
    }
    return ();
}
